# Generated by Django 5.1.6 on 2025-02-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proejcts',
            new_name='Project',
        ),
    ]
