# Generated by Django 5.1.6 on 2025-04-17 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_delete_contactmessage_project_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='github_link',
        ),
    ]
